spring:
  application:
    name: item-service

#server:
#  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      #默认位置，可以修改为具体地理位置，比如：beiJing, shangHai, shenZhen 等，表示 eureka 服务器的部署位置
    registry-fetch-interval-seconds: 30 #拉取注册信息间隔时间，默认 30 秒
  instance:
    lease-renewal-interval-in-seconds: 30 #心跳间隔时间，默认 30 秒

---
spring:
  profiles: item1

server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002